import cgeuclidean_cv_score_classification_crumble
import cgeuclidean_cv_score_classification_nala2
import cgeuclidean_cv_score_classification_eclair
import cgeuclidean_cv_score_classification_cruella




cgeuclidean_cv_score_classification_crumble.main()
cgeuclidean_cv_score_classification_nala2.main()
cgeuclidean_cv_score_classification_eclair.main()
cgeuclidean_cv_score_classification_cruella.main()