import cgeuclidean_cv_score_stratkfold10iteration_classification_cruella
import cgeuclidean_cv_score_classification_zola

cgeuclidean_cv_score_classification_zola.main()
cgeuclidean_cv_score_stratkfold10iteration_classification_cruella.main()
